services:
  - type: web
    name: bookflow-api
    runtime: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /actuator/health
    buildCommand: ""
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_URL
        value: jdbc:postgresql://ep-rough-bird-axvzpu6t-pooler.c-4.us-east-2.aws.neon.tech/neondb?sslmode=require
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_LEHY0ubn3NZC
      - key: JWT_SECRET
        value: bookflowSecretKeyForJwt2026ProductionMin32Chars!!
      - key: CORS_ORIGINS
        value: https://bookflow.h6cy6knypg.workers.dev,http://localhost:5173
