spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookflow_test
    username: bookflow
    password: bookflow123

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true